### PR TITLE
Add unit tests for table reads and write convenience methods

### PR DESCRIPTION
**Pull request by beckerdo**
This commit adds a table read unit test to IonReaderTest and demonstrates how to read and write the table type.

Convenience methods are added to IonWriter to write an entire table row of headers (as keys) and an entire row of data. The row write uses Java reflection to write the proper data type.

### CODE REVIEW

**Comment by jjenkov** [comment]
Hi, thank you for the effort. However, the IonReader and IonWriter are designed to be reflection free APIs. The IonObjectReader and IonObjectWriter use Java reflection to write objects and arrays to ION Object and ION Table fields.

**Comment by beckerdo** [comment]
No worries. Can you guide me to an example or test where you write a table with some headers and rows?

**Comment by jjenkov** [comment]
So far we only have unit tests that write an ION table inside an ION object - but I can't find it just now. Strange. I will get back to you when I find it. Until then, this unit test of the IonWriter has a testTableWriteMethods() which tests the table write methods of the IonWriter.

https://github.com/jjenkov/iap-tools-java/blob/master/src/test/java/com/jenkov/iap/ion/write/IonWriterTest.java

**Comment by jjenkov** [comment]
In general, the visible / public support for ION Tables is still a bit weak. If you create an IonObjectWriter for a class which contains an array of other objects internally (your own objects), then that array will be written to an ION table. So far there is no way to write an ION Table directly. This is of course something that we need to add in the future.

**Pull request closed without merging**
